### ISSUE TITLE
problem help

### ISSUE THREAD

**Issue by 1833631038** [edroaldo/fusca#2]
Does cellcomm have official tutorials?

**Comment by edroaldo** [comment]
We have a tutorial available here: https://github.com/edroaldo/fusca/blob/main/tutorial/CellComm_tutorial.ipynb

We are also preparing other tutorials, which will be available as quickly as possible.

Thank you for your interest.

**Comment by edroaldo** [comment]
Hello, there is a new tutorial available describing initial steps to analyze scRNA-seq data with FUSCA.
https://github.com/edroaldo/fusca/blob/main/tutorial/FUSCA_tutorial_3k_PBMC_ds.ipynb

We will continue writing new tutorials and upload them to github.
