### ISSUE TITLE
clusterPermutation optimization

### ISSUE THREAD

**Issue by NicholasCorneau** [edroaldo/fusca#20]
Hi!

I have been trying to apply CellComm to my single cell data and I found myself having issues with the clusterPermutation function. Mainly, I had a very large number of potential interactions (~600 000), so computing the permutations was prohibitively long. In fact, I tried running CellComm on one of my dataset with a node containing 48 cores for 12 hours and it still hadn't finished computing after the 12 hours. So, I tried to optimize the clusterPermutation function since I knew that it was the computation bottleneck. 

I found a quick fix for the current function such that it does the exact same thing, but in a fraction of the time. I found that the big problem with the current function is that it's iterating through every row of the interactions table (which might be very large like in my case) and then, for every iteration, it's accessing a list element (mean.expr) which is inefficient. The first fix is to create a matrix to store the data that is currently stored in the mean.expr list because it isn't essential to have a list element and I assume that accessing data through a matrix is much faster. The second fix is to apply vectorized functions to the dataframe instead of iterating through every row which saves a tremendous amount of time.

Applying both of these changes allowed for my script to run in less than an hour with 48 cores which is a very big improvement from the current function. I will post the changes I did, so that maybe you can change your function or at the very least to help people in the same position as me. The part that I changed in the clusterPermutation() function are lines 35 to 45. 

```
mean_expr_matrix <- matrix(, nrow=length(mean.expr),
                               ncol=length(genelist),
                               dimnames=list(names(mean.expr),
                                             genelist))

# For each cell type, add the mean gene expression values to the matrix
for(i in c(1:length(mean.expr))) {
  mean_expr_matrix[i, ] <- mean.expr[i][[names(mean.expr[i])]][[2]]
}

# interactions <- population.pairing(mean.expr = mean.expr, ligands=ligands,
#                                    receptors=receptors, threshold = 0.25, pairs.m)
interactions2 <- interactions
interactions2$mean.ligand <- c(1:nrow(interactions2))
interactions2$mean.receptor <- c(1:nrow(interactions2))

fun_apply_ligand <- function(x) {
  mean_expr_matrix[interactions2[x, "celltype1"],
                   interactions2[x, "ligand"]]
}

fun_apply_receptor <- function(x) {
  mean_expr_matrix[interactions2[x, "celltype2"],
                   interactions2[x, "receptor"]]
}

interactions2[, "mean.ligand"] <- sapply(interactions2[,"mean.ligand"],
                                         fun_apply_ligand)
interactions2[, 'mean.receptor'] <- sapply(interactions2[,"mean.receptor"],
                                           fun_apply_receptor)
```
I hope this will be helpful to you!

**Comment by edroaldo** [comment]
Thank you so much, Nicholas!
We are updating CellComm at the moment based on your suggestions and hope
to update github this week!

Thanks!

**Comment by edroaldo** [comment]
We updated the function based on your suggestions. Thank you!

**Comment by NicholasCorneau** [comment]
Hi!

I forgot to say that I also changed the calculatePvalue() function with similar optimization as with clusterPermutation(). This block of code is meant to replace lines 32 - 47:
```
  for(pair in names(pcc)) {
    tmp2[[pair]] <- pair
  }
  
  fun_apply <- function(x) {
    pair.observed <- interactions2[which(interactions2$split == x), ]
    pair.mean.observed <- interactions2[which(interactions2$split == x), 'mean']
    num.higher <- pcc[[x]][which(pcc[[x]]$mean >= pair.mean.observed), ]
    pair.observed$pvalue <- (1+nrow(num.higher))/(1+nPerm)
    pair.observed
  }
  
  tmp2 <- lapply(tmp2, fun_apply)
```

**Comment by edroaldo** [comment]
Thank you! We pushed your suggestions to github!
We appreciate your suggestions!

Thanks!
