### ISSUE TITLE
How to get the mitab dataset

### ISSUE THREAD

**Issue by GilbertHan1011** [edroaldo/fusca#3]
Hello, I'm running the code in the [notebook](https://github.com/edroaldo/fusca/blob/main/tutorial/CellComm_tutorial.ipynb) with my own dataset. However, a problem stuck me in at the step18 **create/define a protein-protein interaction network**.
```R
filename <- "9606.mitab.05-29-2019_zcat.txt"

inetwork <- createPPI(filename = filename, expr = cellrouter@assays$ST@ndata)
```

How can I get this file? I try to download at [iRefIndex](https://irefindex.vib.be/wiki/index.php/README_MITAB2.6_for_iRefIndex) website,but this website seems to have crashed. I look all over the internet and fail to download the ppi dateset of Mus Musculus.

I'd be more than happy if you can help me solve this issue.

**Comment by edroaldo** [comment]
Hello!

Thank you for your interest in using our software! We are working to make any missing files associated with the analysis available as quickly as possible.

I will let you know when this is available.

Thanks!

**Comment by GilbertHan1011** [comment]
Thanks Edroaldo!
I downloaded mouse PPI here [MIPPIE](http://cbdm-01.zdv.uni-mainz.de/~galanisl/mippie/download.php) and changed some code to let it work.
And here are other bugs.
1. when the variables in _cell type_ column have space or underscore, the code will have so many bugs. And it takes me long to fix it.
2. When I run the code at STEP 20 _Find paths between sources (receptors) and targets (transcription factors)_, I failed to run _findpaths.simpleRJava_ function ang got the warning _No cells in the path. The gaph was not created._ every time. And there is no subnet generated at all! 

If there are any solutions plz tell me! Thanks!

**Comment by edroaldo** [comment]
Hello Gilbert,

Thank you for identifying these bugs. My apologies. I did not know that you
have mouse data.
We will work to fix them as soon as possible.  In the meantime, could you
please try changing your cell type names to remove any spaces and follow
the nomenclature from our tutorial in github?

You can also find a mouse PPI here, which I have previously tested.
https://drive.google.com/file/d/1NFULhAmWGfaeWNGTDtW6KpvRMoYMBIsv/view?usp=sharing

I believe the error you are getting with *Find paths* is related to the
fact that you might be using human ligand receptor pairs? If so, please see
also this list using gene symbols converted from human to mouse.
https://drive.google.com/file/d/1t-Bp1_ozjJVTUICXPeeF_wOdWaFMot2d/view?usp=sharing

Then, you can use the following code to open the file and continue the
tutorial:
--
lr_network <- readRDS("Mouse_Ligand_Receptor_Pairs.rds")
receptors <- unique(lr_network$to)
ligands <- unique(lr_network$from)
receptors <- intersect(receptors, ***@***.******@***.***))
ligands <- intersect(ligands, ***@***.******@***.***))
ligand.receptors <- unique(c(ligands, receptors))

mean.expr <- computeValue(cellrouter, assay.type = 'RNA',
genelist=ligand.receptors, column = 'cellcomm', fun='mean'); gc();

## Other tutorial code ##

Please, let me know if that helps. Thank you!

**Comment by GilbertHan1011** [comment]
Thanks for you generous help! It really helps!

I try with the update files and here are my feedbacks.

1. The mitab file from the download link above works, but it gave warnings _“NAs introduced by coercion”_. I don't think this is the best choice. The file from [MAPPIE](http://cbdm-01.zdv.uni-mainz.de/~galanisl/mippie/downloads/mippie_ppi_v1_0.tsv) works better for me.
2. It turns out the warning "No cells in the path. The gaph was not created." is due to the low number of PPI interactions. I lower the threshold of **cellnetworksPPI2** function and it works. But I don't know whether this solution will bring some terrible consequence, and what threshold is accetable.

Thanks again for your patient answers！

Gilbert

**Comment by edroaldo** [comment]
OK. 

1-We will also incorporate the MAPPIE network in FUSCA. 

2-The thresholds are based on positive gene-gene correlations, which we use to create a weighted protein interaction network. Ideally, you keep more highly correlated genes for your downstream analysis. There is no way to define acceptable thresholds given the variety of studies that CellComm can be applied. We extensively tested experirmentally CellComm's predictions. After obtaining the results you can check more specifically the expression of the prioritized genes, or intermediate genes in the path from cell surface to transcriptional regulators. We typically iterate over this process a few times before elaboraing a testable hypothesis from the analysis.

Hope it helps.

Thanks!

**Comment by GilbertHan1011** [comment]
Thanks! It helps!
